//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAplikacija.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFAplikacija.Lang.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string AFButtonBills {
            get {
                return ResourceManager.GetString("AFButtonBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string AFButtonComplete {
            get {
                return ResourceManager.GetString("AFButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string AFButtonProducts {
            get {
                return ResourceManager.GetString("AFButtonProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string AFButtonProperties {
            get {
                return ResourceManager.GetString("AFButtonProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string AFButtonSend {
            get {
                return ResourceManager.GetString("AFButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string AFCurrentLanguage {
            get {
                return ResourceManager.GetString("AFCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL.
        /// </summary>
        public static string AFLabelBill {
            get {
                return ResourceManager.GetString("AFLabelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check server.
        /// </summary>
        public static string AFLabelCheckServer {
            get {
                return ResourceManager.GetString("AFLabelCheckServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language.
        /// </summary>
        public static string AFLabelCurrentLanguage {
            get {
                return ResourceManager.GetString("AFLabelCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom REST request.
        /// </summary>
        public static string AFLabelCustomREST {
            get {
                return ResourceManager.GetString("AFLabelCustomREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press send.
        /// </summary>
        public static string AFLabelPressSend {
            get {
                return ResourceManager.GetString("AFLabelPressSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmable button.
        /// </summary>
        public static string AFLabelProgrammableButton {
            get {
                return ResourceManager.GetString("AFLabelProgrammableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample login.
        /// </summary>
        public static string AFLabelSampleLogin {
            get {
                return ResourceManager.GetString("AFLabelSampleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL:.
        /// </summary>
        public static string AFLabelTotal {
            get {
                return ResourceManager.GetString("AFLabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AFLabelUsername {
            get {
                return ResourceManager.GetString("AFLabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CocaCola.
        /// </summary>
        public static string AFProductCocaCola {
            get {
                return ResourceManager.GetString("AFProductCocaCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite.
        /// </summary>
        public static string AFProductSprite {
            get {
                return ResourceManager.GetString("AFProductSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        public static string AFProductTypeDrink {
            get {
                return ResourceManager.GetString("AFProductTypeDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string AFProductTypeFood {
            get {
                return ResourceManager.GetString("AFProductTypeFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string AFTabAdmin {
            get {
                return ResourceManager.GetString("AFTabAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string AFTabReports {
            get {
                return ResourceManager.GetString("AFTabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string AFTabSale {
            get {
                return ResourceManager.GetString("AFTabSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LFLanguage {
            get {
                return ResourceManager.GetString("LFLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LFLogin {
            get {
                return ResourceManager.GetString("LFLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Cashapp.
        /// </summary>
        public static string LFLoginMessage {
            get {
                return ResourceManager.GetString("LFLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LFPassword {
            get {
                return ResourceManager.GetString("LFPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button to login.
        /// </summary>
        public static string LFPressButton {
            get {
                return ResourceManager.GetString("LFPressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LFUsername {
            get {
                return ResourceManager.GetString("LFUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string PFAction {
            get {
                return ResourceManager.GetString("PFAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string PFActionDelete {
            get {
                return ResourceManager.GetString("PFActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string PFActionEdit {
            get {
                return ResourceManager.GetString("PFActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert product.
        /// </summary>
        public static string PFActionInsert {
            get {
                return ResourceManager.GetString("PFActionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose product.
        /// </summary>
        public static string PFChooseProduct {
            get {
                return ResourceManager.GetString("PFChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string PFComplete {
            get {
                return ResourceManager.GetString("PFComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashapp Properties.
        /// </summary>
        public static string PFNameofForm {
            get {
                return ResourceManager.GetString("PFNameofForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PFPrice {
            get {
                return ResourceManager.GetString("PFPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PFProductID {
            get {
                return ResourceManager.GetString("PFProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Manager.
        /// </summary>
        public static string PFProductManager {
            get {
                return ResourceManager.GetString("PFProductManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PFProductName {
            get {
                return ResourceManager.GetString("PFProductName", resourceCulture);
            }
        }
    }
}
